config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'profile', to: 'users#profile'
  root to: 'users#feed'


  get '/feed', to: 'wishes#index'
  get '/search_following', to: 'users#search_following'
  get '/', to: 'users#show'
    # post '/follow_to', to: 'users#follow_to', as: 'follow'
    # match '/follow_to',    to: 'users#follow_to', as: 'follow',   via: 'get'

  # get '/users/:id', to: 'users#show'
  resources :users do
    post '/follow/:id', to: 'users#follow_to', as: :follow
    post '/no_follow/:id', to: 'users#nofollow_to', as: :nofollow
    resources :followings
      resources :wishes
  end

  resources :wishes, only: :show

  match '/signup',    to: 'users#new',    via: 'get'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/following.rb
class Following < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # after_create :send_email



  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :wishes
  has_many :followings


  #Validations
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100#" }, default_url: "/images/:style/missing.png"
   validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

 def self.search(search)

   if search
     User.where('name = :query OR email = :query', query: search)
   else
      find(:all)
   end

  #  if search
  #    find(:all, conditions: ['mail || name LIKE ?', "%#{search}%"])
  #  else
  #    find(:all)
  #  end
 end

 private
   def send_email

     WelcomeMailer.welcome_email(self).deliver
   end
end

app/models/wish.rb
class Wish < ApplicationRecord

  belongs_to :user

  #Validations
  validates :title, presence:true
  validates_format_of :link, with: URI::regexp(%w(http https)), allow_blank:true

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100#" }, default_url: "/images/:style/missing_wish.png"
   validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  unless Rails.env.development?
    protect_from_forgery with: :exception
  end


  before_action :configure_permitted_parameters, if: :devise_controller?



  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :preferences, :birthday, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :preferences, :birthday, :avatar])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # GET /users
  def index
    @user = User.find_by(email: params[:search])
    unless @user
      render "no_users_found"
    end
  end

  # GET /users/:id
  def show
    @user = User.find_by(id: params[:id])
    unless @user
      render "no_users_found"
    end
  end

  # GET /feed/
  def feed
    @followed = Following.where(user_id: current_user)
    @followed_user= User.where(id: @followed.pluck(:follow_id))
  end

  # GET /users/new
  def new
    @user = User.new
    render "new"
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "New user added successfully"
      WelcomeMailer.welcome_email(@user).deliver.now
      redirect_to "/users/#{@user.id}"
    else
      render "/users/new"
    end
  end

  # GET /users/:id/edit
  def edit
    @user = current_user
  end

  # PATCH/PUT /users/:id
  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to action: :profile, id: @user.id
    else
      render "edit"
    end
  end

  def destroy
  end

  def profile
    @user = current_user
    render 'users/profile'
  end


  def follow_to
    @followed = Following.new
    @followed.user_id = current_user.id
    @user = User.find_by(id: params[:id])
    @followed.follow_id = @user.id

      if @followed.save
        flash[:notice] = "Estás siguiendo la WishrBox de #{@user.name}"
        redirect_to user_wishes_path(@user)
      else
        flash[:notice] = "Ha habido algún error al seguir a #{@user.name}"
        redirect_to user_wishes_path(@user)
      end

  end

  def nofollow_to
      @user = User.find_by(id: params[:id])
      @followed = Following.find_by(user_id: current_user.id, follow_id: @user.id)
      if @followed.destroy
        flash[:notice] = "Ya no sigues a #{@user.name}"
        redirect_to user_wishes_path(@user)
      else
        flash[:notice] = "Ha habido algún error al dejar de seguir a #{@user.name}"
        redirect_to user_wishes_path(@user)
      end
  end



  private
    def user_params
      params.require(:user).permit(:name, :email, :preferences, :birthday, :avatar)
    end
  end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController
  before_action :authenticate_user!


    def index

      if params[:user_id]
        @user = User.find(params[:user_id])
        if current_user.id == params[:user_id].to_i
          @wishes = @user.wishes.order('favorite desc')
        else
          @wishes = @user.wishes.where(public:true).order('favorite desc')
        end
      else
        @user = current_user
        @wishes = @user.wishes.order('favorite desc')
      end

    end

    def new
      @user = current_user
      @wish = @user.wishes.new
    end

    def create
      @user = current_user
      @wish = @user.wishes.new(wish_params)

        if @wish.save
          flash[:notice] = "Deseo añadido a tu WishrBox"
          redirect_to user_wishes_path(@user)
        else
          render "new"
        end
    end

    def edit
      @user = current_user
      @wish = @user.wishes.find params[:id]
    end

    def update
      @user = User.find(params[:user_id])
      @wish = @user.wishes.find_by(id: params[:id])

      if @wish.update(wish_params)
        redirect_to user_wishes_path(@user)
      else
        render "edit"
      end
    end

    def destroy
      @user = current_user
      @wish = @user.wishes.find_by(id: params[:id]).destroy
      redirect_to action: :index, user_id: @user.id
    end

    def show
      @wish = Wish.find_by(id: params[:id])

      unless @wish
        return render text: 'Not Found', status: '404'
      end

      if !@wish.public && @wish.user_id != current_user.id
        return render text: 'Not public', status: '404'
      end

      @user = @wish.user

  end

  def favorite_wishes
    @favorite_wishes = wishes.where(favorite: true)
  end

private

  def wish_params
    params.require(:wish).permit(:title, :description, :link, :price, :image, :locked, :public, :favorite)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wishes_helper.rb
module WishesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WishrBox</title>
    <%= csrf_meta_tags %>
    <link href="//fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Mobile optimization -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <!-- Alerts and validations -->
    <% if alert %>
    <div class="card-panel" id="alert">
      <p class="white-text"><%= alert %></p>
    </div>

    <script>

      setInterval(function () {
        $("#alert").fadeOut()
      }, 5000);
    </script>

    <% end %>

    <% if user_signed_in? %>
    <nav>
      <div class="nav-wrapper">
        <a href="/" class="brand-logo">WishrBox</a>
        <a href="#" data-activates="mobile-demo" class="button-collapse">
          <i class="material-icons">menu</i>
        </a>
        <% if user_signed_in? %>
        <ul class="right hide-on-med-and-down">
          <li><%= link_to 'Inicio', root_path(@user) %></li>
          <li><%= link_to 'Mi WishrBox', user_wishes_path(current_user) %></li>
          <li>
            <a href="#">Deseos Bloqueados</a>
          </li>
          <li><%= link_to "Mi perfil", profile_path(current_user) %></li>
          <li>
            <a href="/search_following">Buscar a tus amigos</a>
          </li>
          <li>
            <% if user_signed_in? %>
            <%= link_to 'Log out', destroy_user_session_path, method: 'DELETE' %></p>
        <% else %>
          <p>
            <%= link_to 'Sign_up', new_user_registration_path %>
            |
            <%= link_to 'Sign_in', new_user_session_path %>
          </p>
          <% end %>
        </li>

      </ul>
      <% end %>

      <% if user_signed_in? %>
      <ul class="side-nav" id="mobile-demo">
        <div class="side-nav-head">
          <%= image_tag current_user.avatar.url(:thumb), class: "avatar-med" %>
          <h5>
            <b><%= current_user.name %></b><br></h5>
          <h5 class="font-small"><%= current_user.email %></h5>
        </div>

        <li><%= link_to root_path(@user) do %>
          <i class="material-icons">home</i>
          Inicio
          <% end %>
        </li>
        <li><%= link_to user_wishes_path(current_user) do%>
          <i class="material-icons">photo_filter</i>
          Mi Wishrbox
          <% end %>

        </li>
        <li>
          <a href="#">
            <i class="material-icons">lock</i>Deseos Bloqueados</a>
        </li>
        <li><%= link_to profile_path(current_user) do%>
          <i class="material-icons">face</i>
          Mi perfil
          <% end %>
        </li>
        <li>
          <a href="/search_following">
            <i class="material-icons">search</i>Buscar a tus amigos</a>
        </li>
        <li>
          <a href="#">
            <i class="material-icons">send</i>Invita a tus amigos</a>
        </li>
        <li><% if user_signed_in? %>
          <%= link_to destroy_user_session_path, method: 'DELETE' do %>
          <i class="material-icons">power_settings_new</i>
          Log out
          <% end %>
        <% else %>

          <%= link_to 'Sign_up', new_user_registration_path %>
          |
          <%= link_to 'Sign_in', new_user_session_path %>

          <% end %>
        </li>
      </ul>

      <% end %>
    </div>
  </nav>
  <% end %>

  <%= yield %>
</body>
</html>

app/views/users/edit.html.erb
<div class="content">
  <div class="edit-user">
    <%= image_tag current_user.avatar.url(:medium), class: "avatar-lg" %>
  </div>

  <div class="edit-user">
    <div class="row">

      <%= form_for @user, html: {multipart: true} do |f| %>
      <div class="input-field col s12">

        <div class="button_with_save_icon valign-wrapper">
          <span class="valign">
            <i class="material-icons">add_a_photo</i>
          </span>
          <%= f.file_field :avatar, class:"edit-user" %>
        </div>

      </div>
      <div class="input-field col s12">
        <%= f.label :name %>
        <%= f.text_field :name, id:"textarea1", class:"materialize-textarea" %>
      </div>
      <div class="input-field col s12">
        <%= f.label :birthday %>
        <%= f.date_field :birthday, id:"textarea1", class:"materialize-textarea" %>
      </div>
      <div class="input-field col s12">
        <%= f.label :preferences %>
        <%= f.text_area :preferences, id:"textarea1", class:"materialize-textarea" %>
      </div>

      <div class="btn-edit-section user-update">
        <%= f.button "Actualizar", class:"waves-effect waves-light btn btn-success" %>
        <%= link_to 'Cancelar', profile_path(@user), class:"waves-effect waves-teal btn-flat" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/feed.html.erb
<!-- User favorite wishes -->

<div class="content">
  <div class="home-self-feed-head">
    <div class="flex-vertical-center self-avatar">
      <h2 class="h5 no-margin">
        <b>Deseos guardados</b>
      </h2>
    </div>
    <div class="flex-vertical-center see-all">
      <%= link_to user_wishes_path(current_user), class: "flex-vertical-center" do %>
      Ver todos
      <i class="material-icons">keyboard_arrow_right</i>
      <% end %>
    </div>
  </div>

  <!-- User row -->
  <section class="row wish-row">
    <% current_user.wishes.each do |wish| %>
    <article class="col wish-card">
      <%= link_to user_wish_path(current_user, wish) do%>
      <div class="wish-img">
        <%= image_tag wish.image.url(:medium)%>
      </div>
      <h3 class="h5"><%= wish.title %></h3>
      <% end %>
    </article>
    <% end %>
  </section>

  <!-- Friends favorite wishes -->

  <% @followed_user.each do |followed| %>
  <div>
    <div class="home-friends-feed-head">
      <div class="flex-vertical-center friends-avatar">
        <%= link_to image_tag(followed.avatar.url(:thumb), class: "circle"), user_wishes_path(followed) %>
        <h2 class="h5 no-margin">
          <b><%= followed.name %></b>
        </h2>
      </div>
      <div class="flex-vertical-center show-profile">
        <%= link_to user_path(followed), class:"flex-vertical-center" do %>
        Ver perfil
        <i class="material-icons">keyboard_arrow_right</i>
        <% end %>
      </div>
    </div>

    <section class="row">
      <div class="tab s10 m12 tabs">
        <% followed.wishes.where(public: true).each do |wish| %>
        <article class="col wish-card">
          <%= link_to user_wish_path(followed, wish) do%>
          <div class="wish-img">
            <%= image_tag wish.image.url(:medium)%>
          </div>
          <h3 class="h5"><%= wish.title %></h3>
          <% end %>
        </article>
        <% end %>
      </div>
    </section>
  </div>
  <% end %>

  <%= link_to new_user_wish_path(current_user, @wish), class:"btn-floating btn-large waves-effect waves-light orange" do%>
  <i class="material-icons">add</i>
  <% end %>
</div>

app/views/users/follow_to.html.erb
<h1>Buscador de amigos</h1>
<hr>
<%= form_for @user do |f| %>
<br></br>
<%= f.label :mail %>
<%= f.text_field :mail %>
<%= f.button %>
<% end %>

app/views/users/index.html.erb
<div class="content profile">

  <ul>
    <h3>Amigo encontrado</h3><br>
    <% @user %>
    <li>
      <div class="user-profile">
        <%= image_tag @user.avatar.url(:thumb), class: "avatar-lg" %>
      </div>
      <%= "Usuario: " + @user.name  %></br>
    <%= "e-mail: " + @user.email %><br><br>
    <%= link_to "WishrBox de #{@user.name}", user_wishes_path(@user) %>
  </li>
</ul>
</div>

app/views/users/index_users.html.erb
  <h1>Users</h1>
  <ul>
    <% @users.each do |user| %>
    <li>
      <%= "Usuario: " + user.name + ": " + " | email: " + user.email %>
        <%= link_to 'Ver perfil', profile_path(@user) %>
    </li>
    <% end %>
  </ul>

app/views/users/new.html.erb
<p>Para crear un nuevo usuario, haga "Log out" y registre otro usuario mediante "Log In"</p>
<!-- <h1>Add a new user</h1>

<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |error_msg| %>
      <li><%= error_msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @user do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %>
  <br></br>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br><br>
  <%= f.label :birthday %>
  <%= f.date_field :birthday %>
  <br><br>
  <%= f.label :preferences %><br>
  <%= f.text_area :preferences  %>
  <br><br>

  <%= f.button %>
  <% end %>

<%= link_to 'Ver usuarios', users_path %>

 <a href="/users">Ver usuarios></a> -->

app/views/users/no_users_found.html.erb
<h2>Lo sentimos, no hemos encontrado ningún usuario.</h2><br>

app/views/users/profile.html.erb
<div class="content profile">

  <ul>
    <div class="user-profile">
      <%= image_tag current_user.avatar.url(:medium), class: "avatar-lg" %>
    </div>

    <li>
      <b>Nombre:</b>
      <%= current_user.name %>
    </li>
    <br>
    <li>
      <b>Cumpleaños:</b>
      <% if current_user.birthday.present? %>
      <%= current_user.birthday.strftime("%d-%m-%Y") %>
      <% end %>
    </li>
    <br>
    <li>
      <b>Preferencias:</b>
      <% if current_user.preferences.present? %>
      <%= current_user.preferences %>
      <% end %>
    </li>
    <br><br>
    <% unless @user != current_user %>
    <%= link_to 'Editar perfil', edit_user_path(current_user), class:"waves-effect waves-light btn" %><br>
    <% end %>
  </ul>
</div>
</div>

app/views/users/search_following.html.erb
<div class="content">
  <h1 class="h3">Descubre los deseos de tus amigos</h1>
  <br>
  <div class="row">
    <%= form_tag users_path, class:"col s12", method: 'get' do%>
    <div class="row input-field col s12">
      <p>Introduce el email del amigo que buscas</p>
      <%= text_field_tag :search, params[:search], class:"validate search" %>
      <%= submit_tag "Buscar", name: nil, class:"waves-effect waves-light btn"  %>
    </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="content profile">

  <ul>
    <div class="user-profile">
      <%= image_tag @user.avatar.url(:medium), class: "avatar-lg" %>
    </div>

    <li>
      <b>Nombre:</b>
      <% if @user.name.present? %>
      <%= @user.name %>
      <% end %>
    </li>
    <li>
      <b>Cumpleaños:</b>
      <% if @user.birthday.present? %>
      <%= @user.birthday.strftime("%d-%m-%Y") %>
      <% end %>
    </li>
    <li>
      <b>Preferencias:</b>
      <% if @user.preferences.present? %>
      <%= @user.preferences %>
      <% end %>
    </li>
    <br><br>
    <%= link_to "WishrBox de #{@user.name} ", user_wishes_path(@user), class:"waves-effect waves-light btn" %>

  </ul>

</div>

app/views/wishes/_form.html.erb
<!-- <% if @wish.errors.any? %>
  <ul>
    <% @wish.errors.full_messages.each do |error_msg| %>
    <li><%= error_msg %></li>
    <% end %>
  </ul>
  <% end %> -->
<br>
<div class="row margin-none">

  <!-- form start -->
  <%= form_for [@user, @wish], html: {multipart:true} do |f| %>
  <div class="input-panel row margin-none">
    <div class="row wish-title">
      <div class="input-field col s8">
        <%= f.text_field :title, placeholder: "Nombre del deseo*" %>
        <%= f.label :title, "title", class: "margin-left-none" %>
      </div>
      <div class="input-field file-field col s3 relative" id="add-image">
        <div class="button_with_save_icon add-image-button">
          <i class="material-icons">add_a_photo</i>
          <div class="row">
            <input class="file-path" type="text" disabled>
          </div>
          <%= f.file_field :image %>
        </div>
        <% if @wish.image %>
        <%= image_tag @wish.image.url(:thumb) %>
        <% end %>
      </div>
    </div>

  </div>

  <div class="input-field input-panel row">
    <%= f.text_area :description, placeholder: "Descripción", class:"materialize-textarea", length:300 %>
    <%= f.label :description %>
  </div>

  <div class="input-field input-panel row">
    <%= f.text_field :link%>
    <%= f.label :link %>
  </div>
  <div class="input-field input-panel row">
    <%= f.text_field :price %>
    <%= f.label :price %>
  </div>
  <div class="input-panel row">
    <div class="filled-in fav" id="filled-in-box" checked="checked">
      <% unless @user != current_user %>
      <%= f.check_box :favorite, class:"wish-check" %>
      <!-- <%= f.label :favorite, raw("&#11088") %> -->
      <%= f.label :favorite , image_tag("http://emojipedia-us.s3.amazonaws.com/cache/12/3d/123d40d4b642994adc6cbdd2c4ed1b73.png") %>
      <% end %>
    </div>

    <div class="filled-in public" id="filled-in-box" checked="checked">
      <%= f.check_box :public, class:"wish-check" %>
      <!-- <%= f.label :public, raw("&#127873") %> -->
      <%= f.label :public , image_tag("http://emojipedia-us.s3.amazonaws.com/cache/3e/a7/3ea7e8a6e273da1515819a1e94b4dbcb.png") %>
    </div>

    <div class="filled-in locked" id="filled-in-box" checked="checked">
      <% unless @user == current_user %>
      <%= f.check_box :locked, class:"wish-check" %>
      <%= f.label :public , image_tag("http://emojipedia-us.s3.amazonaws.com/cache/08/a9/08a98c8c9a1040ae760bc1031a4bf9e9.png") %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <%= f.submit "Actualizar", class:"btn-large btn-expanded" %>
  </div>
  <% end %>
</div>

app/views/wishes/edit.html.erb
<div class="background-grey" id="edit-view">
  <div class="container">
    <div class="row margin-none">
      <div class="col s12 m10 l8 offset-l2 offset-m1 center-align">
        <%= render 'form' %>
        <!-- Partial _form.html.erb -->
        <% if @user == current_user %>
        <button class="waves-effect btn-flat text-red"><%= link_to('Eliminar deseo', user_wish_path(@user, @wish),
      method: :delete, data: { confirm: '¿Seguro que quieres eliminar' }) %></button>
      </div>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/wishes/index.html.erb
<div class="content">
  <%= link_to image_tag(@user.avatar.url(:thumb), class: "avatar-lg"), user_path(@user) %>
  <div class="home-self-feed-head">
    <div class="flex-vertical-center">
      <h2 class="h5">
        <b><%= @user.name %></b>
      </h2>
    </div>
    <div class="flex-vertical-center">
      <h2 class="h4 flex-vertical-center">
        <% if @user == current_user %>
        <%= @user.wishes.length %>
        <% else %>
        <%= @user.wishes.where(public: true).length %>
        <% end %>
        deseos</h2>
    </div>
  </div>

  <section class="wrapper">
    <div class="masonry">
      <% @wishes.each do |wish| %>
      <article class="item">
        <div class="wish-img-user">
          <%= link_to image_tag(wish.image.url(:medium)), user_wish_path(@user, wish) %>
        </div>
        <h3 class="h5"><%= wish.title %></h3>
        <% if wish.favorite? %>
        <img class="fav-mini" src="http://emojipedia-us.s3.amazonaws.com/cache/12/3d/123d40d4b642994adc6cbdd2c4ed1b73.png"/>
        <% end %>
        <% unless @user == current_user %>
          <% if wish.locked? %>
          <img class="fav-mini" src="http://emojipedia-us.s3.amazonaws.com/cache/08/a9/08a98c8c9a1040ae760bc1031a4bf9e9.png"/>
          <% else %>
          <img class="fav-mini" src="http://emojipedia-us.s3.amazonaws.com/cache/30/0a/300ab8f972b71e33e42e27c67dc7e7a8.png"/>
          <% end %>
        <% end %>
        <% unless @user != current_user %>
          <% if wish.public? %>
          <img class="fav-mini" src="http://emojipedia-us.s3.amazonaws.com/cache/3e/a7/3ea7e8a6e273da1515819a1e94b4dbcb.png"/>
          <% end %>
        <% end %>
      </li>
    </article>
    <% end %>
  </div>
</section>

<% unless @user != current_user %>
<a>
  <%= link_to new_user_wish_path(@user, @wish), class:"btn-floating btn-large waves-effect waves-light orange" do%>
  <i class="material-icons">add</i>
  <% end %>
</a>
<% end %>

<!-- <div class="btn-friend-section">
  <div class="user-friend">
    <% unless @user != current_user %>
    <%= link_to "Ver tu perfil", profile_path(current_user), class:"waves-effect waves-light btn" %>
  <% else %>
    <%= link_to "Ver perfil #{@user.name}", user_path(@user), class:"waves-effect waves-light btn" %>
    <% end %>
  </div> -->

  <% unless @user == current_user %>
  <% @followed = Following.find_by(user_id: current_user.id, follow_id: @user.id) %>

  <% unless @followed == nil %>
  <div class="user-unfollow">
    <%= link_to "Dejar de seguir #{@user.name}", user_nofollow_path(current_user, @user), method: :post, class:"waves-effect waves-light btn red" %>
  </div>
<% else %>
  <div class="user-follow">
    <%= link_to "Seguir a #{@user.name}", user_follow_path(current_user, @user), method: :post, class:"waves-effect waves-light btn green" %>
  </div>
  <% end %>
  <% end %>

</div>
</div>

app/views/wishes/new.html.erb
<div class="background-grey" id="edit-view">
  <div class="container">
    <div class="row margin-none">
      <div class="col s12 m10 l8 offset-l2 offset-m1 center-align">
        <%= render 'form' %>
        <!-- Partial _form.html.erb -->

      </div>
    </div>
  </div>
</div>

app/views/wishes/show.html.erb
<div class="content">
  <div class="row center-align wish-detail">
    <div class="user-wish-img valign-wrapper">
      <%= image_tag @wish.image.url(:medium), class: "valign center-align"%>
      <div class="user-wish-favorite">
        <% if @wish.favorite? %>
        <img class="fav-mini" src="http://emojipedia-us.s3.amazonaws.com/cache/12/3d/123d40d4b642994adc6cbdd2c4ed1b73.png"/>
        <% end %>
      </div>
      <div class="user-wish-locked">
        <% if @user != current_user %>
        <% if @wish.locked? %>
        <img class="fav-mini" src="http://emojipedia-us.s3.amazonaws.com/cache/08/a9/08a98c8c9a1040ae760bc1031a4bf9e9.png"/>
      <% else %>
        <img class="fav-mini" src="http://emojipedia-us.s3.amazonaws.com/cache/30/0a/300ab8f972b71e33e42e27c67dc7e7a8.png"/>
        <% end %>
        <% end %>
      </div>
    </div>

    <% if @wish.title.present? %>
    <h2 class="h4">
      <b><%= @wish.title %></h2>
    </b>
    <% end %>
    <div class="user-wish-link">
      <% if @wish.link.present? %>
      <a href="<%= @wish.link %>" target="blank">
        <i class="material-icons md-36">link</i>
      </a><br>
      <% end %>
    </div>
    <div class="user-wish-description valign-wrapper">
      <% if @wish.description.present? %>
      <h3 class="h5"><%= @wish.description %></h3>
      <% end %>
    </div>

    <div class="user-wish-price">
      <% if @wish.price.present? %>
      <h3 class="h5"><%= @wish.price %>
        €</h3>
      <% end %>
    </div>

    <%= form_for [@user, @wish], html: {multipart:true} do |f| %>

    <div class="filled-in fav" id="filled-in-box" checked="checked">
      <% unless @user == current_user %>
      <%= f.check_box :locked, class:"wish-check" %>
      <%= f.label :locked , image_tag("http://emojipedia-us.s3.amazonaws.com/cache/08/a9/08a98c8c9a1040ae760bc1031a4bf9e9.png") %>

      <% end %>
    </div>

    <% if @user != current_user %>
    <% if @wish.locked? %>
      <div class="row">
        <%= f.submit "Desbloquear deseo", class:"btn-large btn-expanded" %>
      </div>
      <% else %>
      <div class="row">
        <%= f.submit "Bloquear deseo", class:"btn-large btn-expanded" %>
      </div>
      <% end %>
      <% end %>

    <!-- <% end %> -->


    <% if @user == current_user %>
    <div class="col s12 m10 l8 offset-m1 offset-l2">
      <%= link_to 'Editar', "/users/#{@user.id}/wishes/#{@wish.id}/edit", class:"btn-large btn-expanded edit" %>
    </div>
    <% end %><br><br>

  </div>
</div>
</div>